language: node_js
node_js:
  - node # this means use the latest version
script:
  - yarn build # Just to make sure the build works. Not actually used for anything
# - yarn test (no tests yet for this project)
